### ISSUE TITLE
sh: 23: Syntax error: "(" unexpected

### ISSUE THREAD

**Issue by iaraiapc** [abelsiqueira/jill#1]
olá Abel

Muito legal de sua parte escrever um script para automatizar a instalação da linguagem julia. Quando executo o comando no terminal linux ocorre:

iara@iara-pc:~$ sh -ci "$(curl -fsSL https://raw.githubusercontent.com/abelsiqueira/jill/master/jill.sh)"
sh: 23: Syntax error: "(" unexpected
$

**Comment by abelsiqueira** [comment]
Olá Iara,

Obrigado!

Você tem que tomar cuidado que o comando esteja em uma linha só, você pode
confirmar se está numa linha só?

sent from cell

Em 19 de jan de 2018 20:41, "iara iapc" <notifications@github.com> escreveu:

olá Abel

Muito legal de sua parte escrever um script para automatizar a instalação
da linguagem julia. Quando executo o comando no terminal linux ocorre:

iara@iara-pc:~$ sh -ci "$(curl -fsSL https://raw.githubusercontent.
com/abelsiqueira/jill/master/jill.sh)"
sh: 23: Syntax error: "(" unexpected
$

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/abelsiqueira/jill/issues/1>, or mute the thread

**Comment by iaraiapc** [comment]
Olá Abel
Obrigado pelo retorno :)
...hum.... executei em um opensuse agora pouco e deu certo, instalou tudo certinho. Quando executei No Ubuntu ocorreu o erro que relatei acima.

**Comment by abelsiqueira** [comment]
Também não uso Ubuntu, então não consigo testar. Vou fechar o issue então, já que você conseguiu instalar. Se precisar pode reabrir. Abraço
