### ISSUE TITLE
curl: (60) SSL certificate problem

### ISSUE THREAD

**Issue by liaoran** [abelsiqueira/jill#32]
Excuse me,When installing according to the operation steps of README, the error "curl: (60) SSL certificate problem: self signed certificate" is reported. When SSL is turned off with -k, the installation cannot be performed normally, and no reasonable solution can be found through goolge query. Please advise.

**Comment by abelsiqueira** [comment]
From some searching, it doesn't appear to be a simple issue: https://github.com/Homebrew/legacy-homebrew/issues/6103
Using the `-k` option should fix the problem, but instead of recommending that, since it's officially called the `--insecure` flag, I recommended downloading the whole package in this new commit: e72c87eec7af2c25ddbc7e529cd83eb2ac6f35ea

Thanks for bringing this to our attention, and let me know if you run into problems again.

**Comment by liaoran** [comment]
Thank you very much. I downloaded the entire package, and through searching, I found that many solutions are not working. I feel that it is not the problem of my local computer, but the problem that the server's self-built certificate cannot be verified. This problem can be git clone the entire package It's no harm to solve it.
