### ISSUE TITLE
Question: Why is the user download directory not hidden?

### ISSUE THREAD

**Issue by LilithHafner** [abelsiqueira/jill#61]
From the readme, without sudo and by default `JULIA_DOWNLOAD=$HOME/packages/julias`. Some folks prefer that programs not edit their home directories except for `$HOME/.whatever`, so I'm curious why you chose this particular download location instead of, say, `$HOME/.local/julias`. I'm also curious if you happen to know of some sort of documented standard for where to install user software without root on linux.

**Comment by abelsiqueira** [comment]
Hi @LilithHafner. No real reason. That's just where I used to keep my julias before the script. I'm not opposed to changing this. I don't know of any documented standard.

**Comment by LilithHafner** [comment]
I also don't know of a documented standard, but I prefer `$HOME/.local/julias` because it is closer to `$HOME/.local/bin` and is a hidden directory. I'm somewhat surprised by the lack of a standard on this.

**Comment by LilithHafner** [comment]
Felix Wechsler has also brought up the possibility of downloading Julia into .julia itself. Do you think that is a good idea?

**Comment by abelsiqueira** [comment]
I think it varies a lot, but frequently it is indeed hidden.
- (Linux)brew.sh uses `~/.linuxbrew`
- Miniconda uses `~/miniconda` (not hidden)
- Conda appears to use `~/.conda` (I don't use it)
I have also been `~/bin`.

That said, it's probably smart to move the folder to `$HOME/.local/julias` or something like that. I was even considering rebranding the `julias` folder to `jill`.

> Felix Wechsler has also brought up the possibility of downloading Julia into .julia itself. Do you think that is a good idea?

I don't think that's a good idea, because it would be hijacking the `.julia` folder. Furthermore, I have seen cases where something wasn't working right with the Julia installation, and the best solution would be to delete the `.julia` folder.

Let me know what you decide on UpdateJulia.jl

**Comment by LilithHafner** [comment]
At the end of a discussion on https://github.com/LilithHafner/UpdateJulia.jl/issues/7, for unix other than mac, I decided to utilize @hhaensel's suggestion to use `dirname(dirname(Base.Sys.BINDIR))` (i.e. wherever the user installed), with a fallback by default to `/opt` and `~/.local` for systemwide and userlevel instillations, respectively. Within `/opt` or `~/.local`, the choice of subdirectory (e.g. `julia`, `julias`, `UpdateJulia`/`jill`, or nothing at all) is, in my opinion, not particularly important and as far as I can tell has no clear right answer. I chose no subdirectory, so the executable will be at `/opt/julia-1.7.0/bin/julia` or `~/.local/julia-1.7.0/bin/julia`.

Perhaps this hints to users that `~/.local/julia-1.5.2/` and `~/.local/julia-1.7.0/` are independent and it is safe to delete either if they no longer want that version?

Perhaps users who keep many versions of Julia around are more likely to be looking for Julia than Microsoft Word when browsing `~/.local` and so it is acceptable to pollute the `./local` namespace with various Julia versions?
